branch-defaults:
  master:
    environment: master
global:
  application_name: blahblah
  branch: null
  default_ec2_keyname: aws-key
  default_platform: PHP 7.2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
